import os

DATABASE_NAME = "users.db"
SESSION_PROTECTION = 'strong'
REMEMBER_COOKIE_DURATION = 3600
NEWS_BOT_TOKEN = os.getenv('NEWS_BOT_TOKEN')
ADMIN_CHAT_ID = int(os.getenv('ADMIN_CHAT_ID'))
NEWS_CHANNEL_ID = os.getenv('NEWS_CHANNEL_ID')
PROFILE_BOT_TOKEN = os.getenv('PROFILE_BOT_TOKEN')
WIREGUARD_PUBLIC_KEY = os.getenv('WIREGUARD_PUBLIC_KEY')
WIREGUARD_ENDPOINT = os.getenv('WIREGUARD_ENDPOINT')
NEWS_JSON_FILE = "news.json"
# Profile bot settings
MAX_PROFILES_PER_USER = 3
BOT_TIMEOUT = 30
